version: "4"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server:1
    container_name: music-player-server
    restart: always
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    image: postgres:16.1-alpine
    container_name: music-player-db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "./data/postgres:/data/postgres"
    networks:
      - music-player

    healthcheck:
      test: ["CMD-SHELL", "pq_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres:

networks:
  music-player:
    driver: bridge
